const List<String> fruitKeywords = [
  'apple', 'تفاح',
  'banana', 'موز',
  'orange', 'برتقال',
  'mango', 'مانجو',
  'grape', 'عنب',
  'pineapple', 'أناناس',
  'strawberry', 'فراولة',
  'blueberry', 'توت أزرق',
  'watermelon', 'بطيخ',
  'peach', 'خوخ',
  'pear', 'كمثرى',
  'kiwi', 'كيوي',
  'papaya', 'بابايا',
  'plum', 'برقوق',
  'cherry', 'كرز',
  'apricot', 'مشمش',
  'nectarine', 'نكتارين',
  'pomegranate', 'رمان',
  'coconut', 'جوز الهند',
  'lime', 'ليمون أخضر',
  'lemon', 'ليمون',
  'fig', 'تين',
  'lychee', 'ليتشي',
  'passion fruit', 'فاكهة العاطفة',
  'guava', 'جوافة',
  'dragon fruit', 'فاكهة التنين',
  'jackfruit', 'جاك فروت',
  'durian', 'دوريان',
  'avocado', 'أفوكادو',
  'cranberry', 'توت بري',
  'blackberry', 'توت أسود',
  'raspberry', 'توت العليق',
  'cantaloupe', 'شمام',
  'honeydew', 'شمام العسل',
  'starfruit', 'فاكهة النجمة',
  'tangerine', 'يوسف أفندي',
  'persimmon', 'كاكا',
  'sapodilla', 'سبوديلا',
  'longan', 'لونغان',
  'mulberry', 'توت',
  'boysenberry', 'بويزن بيري',
  'currant', 'عنب الثعلب',
  'gooseberry', 'عنب الثعلب الهندي',
  'date', 'تمر',
  'olive', 'زيتون',
  'kumquat', 'كمكوات',
  'soursop', 'قشطة شائكة',
  'rambutan', 'رامبوتان',
  'bilberry', 'عنبية',
  'acerola', 'كرز باربادوس',
  'elderberry', 'بيلسان',
  'breadfruit', 'فاكهة الخبز',
  'jabuticaba', 'جابوتيكابا',
  'tamarind', 'تمر هندي',
  'bael', 'بيل فاكهة',
  'salak', 'فاكهة الثعبان',
  'miracle fruit', 'الفاكهة المعجزة',
  'marang', 'مارانغ',
  'yuzu', 'يوزو',
  'ugli fruit', 'فاكهة القبيحة',
  'ackee', 'أكي',
  'camu camu', 'كامو كامو',
  'medlar', 'مشملة',
  'quince', 'سفرجل',
  'pitanga', 'بيتانغا',
  'santol', 'سانتول',
  'mangosteen', 'مانغوستين',
  'safou', 'سافو',
  'chempedak', 'تشيمبداك',
  'feijoa', 'فيجوا',
  'tamarillo', 'تمريلو',
  'black sapote', 'سابوت أسود',
  'white sapote', 'سابوت أبيض',
  'chico fruit', 'فاكهة شيكو',
  'horned melon', 'شمام شوكي',
  'naranjilla', 'نارانخيلا',
  'monstera deliciosa', 'مونستيرا ديليشيوسا',
  'mammee apple', 'تفاحة ماميي',
  'sugar apple', 'تفاح سكري',
  'cherimoya', 'شيريمويا',
  'pawpaw', 'باباو',
  'buddha’s hand', 'يد بوذا',
  'rose apple', 'تفاح الورد',
  'ambarella', 'أمباريلا',
  'ilang-ilang', 'يلانج يلانج',
  'velvet apple', 'تفاح مخملي',
  'jostaberry', 'جوستابيري',
  'sea buckthorn', 'نبق البحر',
  'arhat fruit', 'فاكهة الراهب',
  'huckleberry', 'هاكلبيري',
  'surinam cherry', 'كرز سورينام',
  'imbe', 'إمبي',
  'mamey sapote', 'ماميه سابوتي',
  'wood apple', 'فاكهة الخشب',
  'calamansi', 'كلامانسي',
  'barbadine', 'باربادين',
  'abiu', 'أبيو',
  'canistel', 'كانيستل',
  'bignay', 'بيغناي',
  'grumichama', 'غرو ميشاما',
  'pepino melon', 'بطيخ بيبينو',
  'mabolo', 'مابولو',
  'desert lime', 'ليمون الصحراء',
  'snow pear', 'كمثرى الثلج',
  'midyim berry', 'توت ميديم',
  'burdekin plum', 'برقوق بيرديكين',
  'finger lime', 'ليمون الإصبع',
  'mountain pepper', 'فلفل الجبل',
  'illawarra plum', 'برقوق إلوارا',
  'bunya nut', 'جوزة بونيا',
  'fruit', 'فاكهة'
];



